import { ReactNode } from 'react';
import { HeadComponent } from './head-component';
import React from 'react';
import { Footer } from './footer';
import { Toaster } from 'sonner';
import { Navbar } from './navbar';

interface LayoutProps {
  flexDirection?: 'row' | 'col';
  justify?: 'start' | 'end' | 'center' | 'between' | 'around' | 'evenly';
  align?: 'start' | 'end' | 'center' | 'baseline' | 'stretch';
  gap?: number;
  app?: boolean;
}

interface PageLayoutProps extends LayoutProps {
  children: ReactNode;
  title?: string;
  description?: string;
}

export const PageLayout: React.FC<PageLayoutProps> = ({
  children,
  title = 'RainbowKit App',
  description = 'Generated by @rainbow-me/rainbowkit',
  flexDirection = 'col',
  justify = 'start',
  align = 'center',
  gap = 8,
  app = false,
}) => {
  return (
    <>
      <HeadComponent title={title} description={description} />
      <MainContainer flexDirection={flexDirection} justify={justify} align={align} gap={gap} app={app}>
        {children}
      </MainContainer>
    </>
  );
};

const MainContainer: React.FC<LayoutProps & { children: React.ReactNode }> = ({
  children,
  flexDirection = 'col',
  justify = 'start',
  align = 'center',
  gap = 2,
  app = false,
}) => {
  const justifyClass = {
    start: 'justify-start',
    end: 'justify-end',
    center: 'justify-center',
    between: 'justify-between',
    around: 'justify-around',
    evenly: 'justify-evenly',
  }[justify];

  const alignClass = {
    start: 'items-start',
    end: 'items-end',
    center: 'items-center',
    baseline: 'items-baseline',
    stretch: 'items-stretch',
  }[align];

  return (
    <>
      <Navbar />
      <main
        className={`sm:overflow-hidden relative min-h-screen bg-black flex flex-wrap flex-${flexDirection} ${justifyClass} ${alignClass} gap-${gap} pt-16`}
      >
        <div className="h-min md:max-w-7xl w-full relative z-10 bg-black flex flex-col flex-wrap items-center justify-center text-center pb-8 max-w-96 px-4">
          {children}
        </div>
      </main>
      <Toaster />
      <Footer />
    </>
  );
};
